TP5_Grupo10/src/main/resources/templates/agenda.html
TP5_Grupo10/src/main/resources/templates/beneficios.html
TP5_Grupo10/src/main/resources/templates/contacto.html
TP5_Grupo10/src/main/resources/templates/idiomas.html
TP5_Grupo10/src/main/resources/templates/index.html

Desarrollo de actividad 2.

---

TP5_Grupo10/src/main/resources/static/css/style.css

Desarrollo de la actividad 4

---

TP5_Grupo10/src/main/resources/templates/agenda.html
TP5_Grupo10/src/main/resources/templates/beneficios.html
TP5_Grupo10/src/main/resources/templates/contacto.html
TP5_Grupo10/src/main/resources/templates/idiomas.html
TP5_Grupo10/src/main/resources/templates/index.html
TP5_Grupo10/src/main/resources/templates/layouts/footer.html
TP5_Grupo10/src/main/resources/templates/layouts/header.html

Desarrollo de la actividad 6.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/DocenteController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaDocente.java
TP5_Grupo10/src/main/resources/templates/nuevo_docente.html

Desarrollo de la actividad 1 tp5-continuacion.

Desarrollo de la actividad 1 tp5-continuacion.

---

TP5_Grupo10/src/main/resources/templates/lista_docentes.html

Desarrollo de la actividad 3 tp5-continuacion

Desarrollo de la actividad 3 tp5-continuacion

---

TP5_Grupo10/src/main/resources/templates/layouts/header.html

Desarrollo de la actividad 4 tp5-continuacion

Desarrollo de la actividad 4 tp5-continuacion

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/BecaController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaBecas.java
TP5_Grupo10/src/main/resources/templates/layouts/header.html
TP5_Grupo10/src/main/resources/templates/lista_becas.html
TP5_Grupo10/src/main/resources/templates/nuevo_beca.html

Desarrollo de la actividad 5 (becas) tp5-continuacion

Desarrollo de la actividad 5 (becas) tp5-continuacion

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/AlumnoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaAlumnos.java
TP5_Grupo10/src/main/resources/templates/layouts/header.html
TP5_Grupo10/src/main/resources/templates/lista_alumnos.html
TP5_Grupo10/src/main/resources/templates/nuevo_alumno.html

Desarrollo de la actividad 5 (alumnos) tp5-continuacion.

Desarrollo de la actividad 5 (alumnos) tp5-continuacion.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/AlumnoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/BecaController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/CursoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/DocenteController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Beca.java

Desarrollo de la actividad 6 tp5-continuacion.

Desarrollo de la actividad 6 tp5-continuacion.

---

TP5_Grupo10/pom.xml

Desarrollo de la actividad 1 tp5-validaciones.

Desarrollo de la actividad 1 tp5-validaciones.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Alumno.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Beca.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Curso.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Docente.java

Desarrollo de la actividad 2 tp5-validaciones.

Desarrollo de la actividad 2 tp5-validaciones.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/AlumnoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/BecaController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/CursoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/DocenteController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Beca.java

Desarrollo de la actividad 3 tp5-validaciones.

Desarrollo de la actividad 3 tp5-validaciones.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Alumno.java

Desarrollo de la actividad 1 tp5-servicios.

Desarrollo de la actividad 1 tp5-servicios.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Beca.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Curso.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/model/Docente.java

Desarrollo de la actividad 2 tp5-servicios.

Desarrollo de la actividad 2 tp5-servicios.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/AlumnoServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/BecaServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/CursoServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/DocenteServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaAlumnos.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaBecas.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaCursos.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaDocente.java

Desarrollo de la actividad 4 tp5-servicios.

Desarrollo de la actividad 4 tp5-servicios.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/AlumnoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/BecaController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/CursoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/DocenteController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/AlumnoServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/BecaServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/CursoServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/DocenteServiceImp.java

Desarrollo de la actividad 5 tp5-servicios.

Desarrollo de la actividad 5 tp5-servicios.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/AlumnoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/BecaController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/BeneficiosController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/CursoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/DocenteController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/IdiomasController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/IAlumnoService.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/AlumnoServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/BecaServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/CursoServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/DocenteServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaDocente.java
TP5_Grupo10/src/main/resources/templates/contacto.html
TP5_Grupo10/src/main/resources/templates/edicion_alumno.html
TP5_Grupo10/src/main/resources/templates/edicion_beca.html
TP5_Grupo10/src/main/resources/templates/edicion_curso.html
TP5_Grupo10/src/main/resources/templates/edicion_docente.html
TP5_Grupo10/src/main/resources/templates/idiomas.html
TP5_Grupo10/src/main/resources/templates/lista_alumnos.html
TP5_Grupo10/src/main/resources/templates/lista_becas.html
TP5_Grupo10/src/main/resources/templates/lista_cursos.html
TP5_Grupo10/src/main/resources/templates/lista_docentes.html

Desarrollo de la actividad 6 tp5-servicios.

Desarrollo de la actividad 6 tp5-servicios.

---

TP5_Grupo10/pom.xml

Se agregan las dependencias [Spring boot starter data jpa-MySql conector]

Se agregan las dependencias [Spring boot starter data jpa-MySql conector

---

TP5_Grupo10/src/main/resources/application.properties

Modificación en application.properties.

Modificacion en application.properties.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Alumno.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Beca.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Curso.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Docente.java

Actualización Ejercicio 6 Modificación del Mapeo Objeto Relacional

Actualización Ejercicio 6 - Modificación del Mapeo Objeto Relacional

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/AlumnoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/BeneficiosController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/DocenteController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Alumno.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Docente.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/repository/IAlumnoRepository.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/repository/IDocenteRepository.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/IAlumnoService.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/IDocenteService.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/AlumnoServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/DocenteServiceImp.java

Desarrollo Ejercicio 7- Creación del paquete repository y creación las interfaces necesarias (Docente/Alumno).

Desarrollo Ejercicio 7- Creación del paquete repository y creación de

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/repository/IBecaRepository.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/repository/ICursoRepository.java

Desarrollo de actividad 7 Se agregan interfaces Beca-Curso. Implementación incompleta.

Desarrollo de actividad 7 Se agregan interfaces Beca-Curso.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/AlumnoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Alumno.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/AlumnoServiceImp.java
TP5_Grupo10/src/main/resources/templates/edicion_alumno.html

Solucion a problemas de modificacion/eliminacion de alumno.

Solucion a problemas de modificacion/eliminacion de alumno.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/DocenteController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/repository/IDocenteRepository.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/IDocenteService.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/DocenteServiceImp.java
TP5_Grupo10/src/main/resources/templates/edicion_docente.html
TP5_Grupo10/src/main/resources/templates/lista_docentes.html
TP5_Grupo10/src/main/resources/templates/nuevo_docente.html

Modificaciones implementadas para Docente.

Modificaciones implementadas para Docente.

---

TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/AlumnoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/BecaController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/CursoController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/controller/DocenteController.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Alumno.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Beca.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Curso.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/entity/Docente.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/repository/IBecaRepository.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/repository/ICursoRepository.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/IBecaService.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/ICursoService.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/AlumnoServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/BecaServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/service/imp/CursoServiceImp.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaAlumnos.java
TP5_Grupo10/src/main/java/ar/edu/unju/fi/tp5/util/ListaBecas.java
TP5_Grupo10/src/main/resources/templates/edicion_beca.html
TP5_Grupo10/src/main/resources/templates/edicion_curso.html
TP5_Grupo10/src/main/resources/templates/lista_becas.html
TP5_Grupo10/src/main/resources/templates/lista_cursos.html
TP5_Grupo10/src/main/resources/templates/nuevo_alumno.html
TP5_Grupo10/src/main/resources/templates/nuevo_beca.html
TP5_Grupo10/src/main/resources/templates/nuevo_curso.html

Corimayo: Falta solucionar Alumnos.

Corimayo: Falta solucionar Alumnos.

---

TP5_Grupo10/src/main/resources/templates/idiomas.html

Correcciones menu idiomas
